---
- name: Specific VM config
  hosts: webservers
  tasks:
    - name: Copy custom config
      copy:
        src: files/app.conf
        dest: /etc/nginx/sites-available/default
        backup: yes
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
